---
repository:
  name: mdadm
  description: Ansible role to install and configure mdadm RAID manager
  topics: ansible, role, ansible-role, hacktoberfest

  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false

  default_branch: master

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: ffffff
    description: This will not be worked on
  - name: hacktoberfest-accepted
    color: cccccc
    description: Accepted as a Hacktoberfest submission
  - name: renovate
    color: e99695
    description: Automated action from Renovate

branches:
  - name: master
    protection:
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration/drone/pr
      enforce_admins: false
      restrictions:
        users: []
        teams: []

...
