# Standards: 1.2
---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: False
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Destroy molecule instances
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      register: openstack_server
      async: 7200
      poll: 0
      openstack.cloud.server:
        name: "{{ item.name }}"
        state: absent
        delete_fip: True

    - name: Wait for deletion
      loop: "{{ openstack_server.results }}"
      loop_control:
        label: "{{ item.item.name }}"
      register: openstack_jobs
      until: openstack_jobs.finished
      retries: 300
      async_status:
        jid: "{{ item.ansible_job_id }}"

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      when: openstack_server.changed | bool
      copy:
        content: "{{ instance_conf | to_json | from_json | to_yaml }}"
        dest: "{{ molecule_instance_config }}"

...
