---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for apt lock
      shell: while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do echo 'Waiting for apt list lock.' && sleep 10; done
      changed_when: False
