---
name: general

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Role linting
        uses: patrickjahns/ansible-later-action@master
        with:
          config: .later.yml

  testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        scenario:
          - ubuntu

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}

      - name: Molecule tests
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}

...
