---
name: readme

on:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Generate readme
        uses: actionhippie/ansible-doctor@v1
        with:
          force: true
          verbose: true

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: README.md
          message: automated readme update [skip ci]
          push: true
          signoff: true

...
